---
name: Super-Linter

# Run this workflow every time a new commit is pushed to the repository
on: push

jobs:
  # Set job key. This is displayed as job's name when there's no name
  super-lint:
    # Name the job
    name: Lint code base
    # Set the machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Runs the Super-Linter action
      - name: Run Super-linter
        # https://github.com/marketplace/actions/super-linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: .*/lib/.*
          JAVASCRIPT_DEFAULT_STYLE: nothing
          JAVASCRIPT_STYLE: nothing
          VALIDATE_JAVASCRIPT_STANDARD: false
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.yml
          CSS_FILE_NAME: .stylelintrc.json
